### ISSUE TITLE
Create Faucet Module for Osmosis testnet.

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/osmosis#3]
Faucet module. Allows unlimited testnet tokens to be created and sent to the Defiant Labs testnet wallet (and/or other wallets designated by the Osmosis team). Defiant Labs will write and test this module and submit it to the Osmosis team via Pull Request.

**Comment by danbryan** [comment]
Copied comments from old repo

[KyleMoser](https://github.com/KyleMoser) commented [last month](https://github.com/DefiantLabs/osmosis-price-matching/issues/3#issue-1575489127) Create minting module for Osmosis Prove the upgrade handler works in a local Osmosis testnet (e.g. deploy Osmosis v14 or whatever the newest version is, then apply your upgrade handler to upgrade to a newer version w/ your minting module).

[danbryan](https://github.com/danbryan) commented [last month](https://github.com/DefiantLabs/osmosis-price-matching/issues/3#issuecomment-1422055502) Create a mint module - create any amount of any tokens and send to an account.

For minting coins, there are a large amount of mint modules already out there like [noble](https://github.com/strangelove-ventures/noble)

related docs:

[intro to cosmos modules](https://docs.cosmos.network/main/building-modules/intro) [Real module examples](https://github.com/cosmos/cosmos-sdk/tree/main/x) Details

All of the pools have a price, need to match on the testnet In order to make prices match, will need to either: Add liquidity to the pool Trade with the pool The above MAY be situational Need code to make the correct decision Price is ratio of the amounts of the 2 tokens in the pool, depends on the weight of each token Original Discussion notes: [Kyle-Peter-Notes.txt](https://github.com/DefiantLabs/osmosis/files/10681910/Kyle-Peter-Notes.txt)

[pharr117](https://github.com/pharr117) commented [last month](https://github.com/DefiantLabs/osmosis-price-matching/issues/3#issuecomment-1427317110) At a high level, the process for creating the minting module will look like this:

Create/generate new module boilerplate Create proto files listing all required proto types in proto/osmosis/ Generate protobuf (.pb.go) type definition files from global module .proto file using protoc-gen-gogo Proto tooling built in most chain Makefiles at make proto-gen AppModuleBasic type definitions Create Genesis module functions for new module creation functionality Create new Keeper Create KV store setters and getters (if needed) Create Message types Integrate module into main app.go Import new module in main app.go Add module Keeper to AppKeepers struct Initialize Keeper Pass module dependency keepers down to new module (e.g. bank module keeper passed during mint module init) Add store key to KVStoreKeys array

[pharr117](https://github.com/pharr117) commented [last month](https://github.com/DefiantLabs/osmosis-price-matching/issues/3#issuecomment-1430745787) I have just finished the above list of items. What I have locally is a new module named faucet that:

Contains all module boilerplate listed above. This is a very rough MVP and will definitely need updates. Integrates into the base Osmosis Application Builds successfully running make docker-build This means I did not break the build, the osmosis chain compiled successfully Runs all tests successfully running make test This means I did not break the test, all current Osmosis tests pass successfully I was hoping to implement the keeper code to make an MVP, but the above took slightly longer than I thought it would.

[pharr117](https://github.com/pharr117) commented [last month](https://github.com/DefiantLabs/osmosis-price-matching/issues/3#issuecomment-1430749645) https://github.com/DefiantLabs/osmosis/tree/faucet-module-boilerplate

[danbryan](https://github.com/danbryan) commented [3 weeks ago](https://github.com/DefiantLabs/osmosis-price-matching/issues/3#issuecomment-1432261956) Curious, does it mint tokens yet?

[pharr117](https://github.com/pharr117) commented [3 weeks ago](https://github.com/DefiantLabs/osmosis-price-matching/issues/3#issuecomment-1433970590) Not yet, that's the last piece for the MVP. I already have an example of how to do it in Noble that Kyle linked me. I will transition back over to that after working on my current Sycamore site update.

[pharr117](https://github.com/pharr117) commented [2 weeks ago](https://github.com/DefiantLabs/osmosis-price-matching/issues/3#issuecomment-1441185428) The basic boilerplate for the minting module is finished, and it is now in MVP state.

I will be extending it with architecture requirements and improvements as required by the team, and I will be splitting those out into separate tickets.

You can see the current state of the module at this fork branch here:

https://github.com/DefiantLabs/osmosis/tree/faucet-module-boilerplate

**Comment by pharr117** [comment]
At this point, the module is in the following state:

### Proto definitions

1.  Msg service with 3 rpc endpoints for FaucetMint, AddFaucetAddress and RemoveFaucetAddress
2. Query service with 1 rpc endpoint for GetFaucetAddresses
3. GenesisState with a list of address strings for Module Genesis whitelist address setting
4. FaucetAddress message type to use as the storage type for the whitelisted addresses

### Module Boilerplate

1. New module boilerplate interface definitions
2. Integration of module into the base app in the Osmosis preferred way

### Module Genesis

I have added Init and Export functionality to load addresses from the genesis file into the module KV Store and to gather the addresses on export.

### Module Functionality

1. msgServer and Keeper implementation for FaucetMint: uses the bank keeper to mint and send coins to the address specified as the transaction sender
2. Implementation for AddFaucetAddress: Interfaces with the module KV Store to store a new address on the whitelist
4. Implementation for RemoveFaucetAddress: The same as (2) but for removing
5. Whitelist security layer for (1) - (3): Checks the module KV store for the sender of each transaction type, errors if the sender is not in the whitelist
6. Query service and Keeper functionality for GetFaucetAddresses: loops through and returns all addresses found in the module KV Store

### Client Functionality

1. Transaction CLI implementations for FaucetMint, AddFaucetAddress and RemoveFaucetAddress commands
2. Query CLI implementation for GetFaucetAddresses

### LocalOsmosis Changes

I have modified one file in the `localosmosis` testing setup:

1. Modify the `edit_genesis` function to update the  genesis.json state file used by the localosmosis docker instance on application genesis
2. Add a single address to the faucet module genesis state to allow `localosmosis` manual testing of the module
