### ISSUE TITLE
Add address administration to faucet module

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/osmosis#5]
The module needs a way to add and remove addresses from a whitelist.

The behavior should be like this:

Only addresses in the whitelist should be able to use the faucet module minting functionality
Only addresses in the whitelist should be able to add new addresses to the whitelist
Only addresses in the whitelist should be able to remove addresses
An address cannot remove itself
Removing the last address should be impossible (redundant from 4 anyways)
This will require getting familiar with the way Cosmos uses its KV store on a per-module basis, as this will be used for storing and interacting with the module whitelist.

**Comment by danbryan** [comment]
adding comments from old repo.

[pharr117](https://github.com/pharr117) commented [2 weeks ago](https://github.com/DefiantLabs/osmosis-price-matching/issues/4#issuecomment-1441232692) • 
I have already added the boilerplate proto file updates and message types/handlers for this part, and now just need to implement the actual functionality as described above.

I will be taking a look through Noble's implementation of their tokenfactory module admin functionality.

They seem to be following a similar workflow to our requirements, so I will be able to use it for examples on this task.

[Here](https://github.com/strangelove-ventures/noble/blob/main/x/tokenfactory/keeper/minters.go), for example, is how they interact with the KV store.

**Comment by pharr117** [comment]
Update for this one:

* I have added 2 transactions to the faucet module
  * 1 for adding addresses to whitelist
  * 1 for removing addresses from whitelist
* I have implemented a whitelist check on all transactions for the faucet module, it makes sure the sender of the TX is in the whitelist before allowing any of the 3 transactions from proceeding

The final step for this will be to add query functionality to return the list of addresses stored in the faucet module whitelist.

**Comment by pharr117** [comment]
I have implemented the query functionality for getting the list of addresses in the whitelist.

I am marking this one as done due to the above comment and this one.
