### ISSUE TITLE
Research how to create new cosmos modules on existing blockchains (Osmosis)

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/osmosis#7]
[pharr117](https://github.com/pharr117) commented [last month](https://github.com/DefiantLabs/osmosis-price-matching/issues/2#issuecomment-1426827502) • 
Here is what I have done and learned on this one so far:

Cosmos provides high-level documentation on how to build modules properly.
[Documentation here](https://docs.cosmos.network/v0.47/building-modules/intro)
I have read this basically end-to-end. It is very high-level, without giving full details on exactly what needs to happen.
This is in my opinion a good overview as it explains all the concepts well, but to actually do the work I need real world documentation.
According to the Cosmos SDK docs, In-Place Store Migrations are the process to to add new modules as wells as upgrade old modules to new versions that contain breaking changes.
Upgrading old modules
[Documentation here](https://docs.cosmos.network/v0.47/core/upgrade)
The Cosmos upgrade module provides a concept of Consensus Version
Old modules will already have a current ConsensusVersion
When Cosmos detects a new ConsensusVersion for a module, this indicates a breaking change that needs special handling
Cosmos will run any migration code found in the breaking upgrade module's UpgradeHandler (e.g., updating KV store values if needed)
The process for adding new modules is slightly different.
[Cosmos documentation here](https://docs.cosmos.network/v0.47/core/upgrade#adding-new-modules-during-upgrades)
New modules are recognized since they are not in the upgrade module's VersionMap store
With new modules, the upgrade handler code will run the module's InitGenesis function to set up initial state
The application will then need to add store upgrades for the new modules (since each module gets its own KV store)
After finding and reading all this documentation, my research has turned to the following:

Figure out what the boilerplate is:
Each module has common code that must be in place before integrating the new module
This is due to the extensive use of common interfaces to define modules.
Figure out how to create the boilerplate:
Cosmos provides a tool called [Ignite](https://docs.ignite.com/) that aims to make it easy to spin up chains (and modules)
I need to figure out if this is the standard and if we can use this in Osmosis particularly
It should handle a lot of the boilerplate of setting up the module
For things like proto type definitions:
The community seems to be using automated tooling to generate .pb.go files from .proto files
I am still trying to figure out how to do this step, but it is important.
See [here](https://github.com/strangelove-ventures/noble/blob/main/x/tokenfactory/types/blacklisted.pb.go#L1) for an example of an autogenerated file
Figure out how to build and test the new module locally
Building and testing locally will ensure it works before pushing the changes to the upstream
I will be writing tests according to the [Cosmos testing guide](https://docs.cosmos.network/v0.47/building-modules/testing)
This will involve unit, integration and simulation tests which will ensure the module functions correctly
The above 3 points are high-level overviews of my research, there are a lot more details to consider that I will write out later.

[pharr117](https://github.com/pharr117) commented [last month](https://github.com/DefiantLabs/osmosis-price-matching/issues/2#issuecomment-1426860090) • 
I am currently compiling a list of resources which will be useful in creating the module, and I will update this comment if I find more:

Noble chain's initial commits with tokenfactory module boilerplate
[first](https://github.com/strangelove-ventures/noble/commit/46d09f6a251b45f0b5c7716249aa4f1416ccee7a)
[second](https://github.com/strangelove-ventures/noble/commit/432bcd99926ed9efef60b58559aa8f1d4ebf8ede)
They seem to be using Ignite CLI as I detailed above
Cosmos tutorials for building chains [here](https://tutorials.cosmos.network/tutorials/1-tech-terms/)
Heavy usage of Ignite CLI
Details end-to-end usage of Ignite to build a chain from the ground-up. Will need to pick out the relevant sections.
A Medium article written by an Evmos dev about creating modules [here](https://medium.com/web3-surfers/cosmos-dev-series-cosmos-sdk-based-blockchain-upgrade-b5e99181554c#f7d3)
Pretty heavy on the upgrading modules over adding new modules, but has good info
Documentation of end-to-end building of modules by a Kava dev [here](https://docs.kava.io/docs/cosmos/building-modules/)
Basically details the entire process of module building
Could be Kava specific in areas, but has a good complete rundown
A recent module addition in Osmosis, this PR introduced the Downtime Detector module
[PR here](https://github.com/osmosis-labs/osmosis/pull/3688/files)

[pharr117](https://github.com/pharr117) commented [last month](https://github.com/DefiantLabs/osmosis-price-matching/issues/2#issuecomment-1427273933) • 
After doing some preliminary tests of module building, I am running into issues with Ignite CLI and Osmosis.

The tool offers a way to scaffold out new modules like so:

ignite scaffold module faucet --dep bank
We need to have a dependency of the base Cosmos SDK bank module to create new coins.

This results in the following error:

The module cannot have Bank as a dependency: app doesn't contain BankKeeper
Which is completely false. I think the Ignite runtime dependency check is broken, at least in Osmosis, and is not finding the base Cosmos modules. It could be the way Osmosis is setup.

I will probably have to scaffold out the module myself.

**Comment by danbryan** [comment]
@pharr117 Please link a PR to this ticket under development, if applicable then close

**Comment by pharr117** [comment]
Research phase was completed, no branch/PR link needed
