### ISSUE TITLE
Research noble chain's minting module

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/osmosis#8]
[KyleMoser](https://github.com/KyleMoser) commented [last month](https://github.com/DefiantLabs/osmosis-price-matching/issues/1#issue-1575486629)
Figure out how noble's minting module works so we can write a mint module for osmosis.

We will want configurable (e.g. in a TOML file) "starter" list of addresses that are allowed to mint tokens (if this isn't how it works, lets discuss what the options are)
It would be nice if the pre-configured addresses are allowed to add/remove other addresses from the list (e.g. via a TX). Not required, this would be an extra above & beyond but I think Osmosis would like it.
The mintable list of tokens should probably be configurable by an admin, but we can talk about it if this isn't how noble's works

**Comment by danbryan** [comment]
[pharr117](https://github.com/pharr117) commented [last month](https://github.com/DefiantLabs/osmosis-price-matching/issues/1#issuecomment-1424995863) • 
Here is what I have learned so far on this one, particularly on how they mint new coins:

The noble chain implements a tokenfactory module. [Implementation](https://github.com/strangelove-ventures/noble/tree/main/x/tokenfactory).

This module has a MsgMint type that implements the message for minting coins. [Implementation](https://github.com/strangelove-ventures/noble/blob/main/x/tokenfactory/types/message_mint.go).

Here they do the basic interface methods for Cosmos messages, particularly ValidateBasic which handles the pre-validation of message parameters.
The keeper of the module contains the actual source that handles the minting process. [Implementation](https://github.com/strangelove-ventures/noble/blob/main/x/tokenfactory/keeper/msg_server_mint.go).

At a high level, the process they do is this:

Calls cosmos-sdk types function called NewCoins to create a new amount of coins
Passes this amount to the base Cosmos bank module keeper MintCoins function
Comment on this function in the cosmos-sdk code: // MintCoins creates new coins from thin air and adds it to the module account
This creates coins and adds it to the Bank module’s supply
Then calls the base Cosmos Bank module keeper function SendCoinsFromModuleToAccount
This does exactly what it sounds like, sends the newly minted coins to the account specified as the receiver
Its pretty straightforward when you understand the terminology and what functions to call and where.

**Comment by danbryan** [comment]
[pharr117](https://github.com/pharr117) commented [last month](https://github.com/DefiantLabs/osmosis-price-matching/issues/1#issuecomment-1427319689)
Noble used the Ignite CLI tool to create their module. Unfortunately, the same process is not working when I try to use it in the Osmosis repo.

I believe this has something to do with Ignite's module reader and the way Osmosis has structured their codebase.

I will have to make the module manually instead, which should not be too difficult with the amount of research I have put in.

**Comment by danbryan** [comment]
[pharr117](https://github.com/pharr117) commented [last month](https://github.com/DefiantLabs/osmosis-price-matching/issues/1#issuecomment-1427320134)
Marking this one as done, I have figured out how Noble's mint module works enough to do the work needed when I get to actually implementing the logic to create new coins.

**Comment by danbryan** [comment]
@pharr117 Please link a PR to this ticket under development, then close

**Comment by pharr117** [comment]
Research phase was complete, no branch/PR link needed
